# Setup
title: dsillman
tagline: David Sillman's personal website
url: https://www.dsillman.com
domain: dsillman.com
baseurl: ""
permalink: pretty

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true

compress_html:
  blanklines: false

# Gems
plugins:
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - _css
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - AGENTS.md
  - .opencode
  - .github
  - Makefile
  - compile-favicon.sh

# Specify the author for blog posts
author:
  name: David Sillman
  url: https://github.com/dsillman2000

# Custom vars
repository: https://github.com/dsillman2000/dsillman2000.github.io
