markdown: kramdown
highlighter: rouge

domain: dsillman.com
url: https://www.dsillman.com

kramdown:
  input: GFM
  auto_ids: true

compress_html:
  blanklines: false

plugins:
  - jekyll-last-modified-at

exclude:
  - _css
  - node_modules
  - package.json
  - package-lock.json
  - Makefile
  - readme.md
  - .github
