source "https://rubygems.org"

gem "webrick", "~> 1.7"
gem "jekyll-watch", "~> 2.2"
gem "kramdown-parser-gfm", "~> 1.1"
gem "jekyll", "~> 4.2"
gem "jekyll-last-modified-at"
gem "jekyll-gist"
gem "jekyll-paginate"
gem "jekyll-seo-tag"
gem "faraday-retry"
