markdown: kramdown
highlighter: rouge

domain: dsillman.com
url: https://www.dsillman.com
# baseurl: "dsillman2000.github.io"

kramdown:
  input: GFM
  auto_ids: true
  # syntax_highlighter: rouge

sass:
  sass_dir: _sass

compress_html:
  blanklines: false

plugins:
  - jekyll-postcss-v2

postcss:
  cache: false
